# Generated by Django 5.2.1 on 2025-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('validado_por', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('fuente', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
            ],
        ),
    ]
