# Generated by Django 5.2.1 on 2025-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('validado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('fuente', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
