# Generated by Django 5.2.1 on 2025-05-14 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_alter_solicitud_options_solicitud_comentario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_subida',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_usuario',
            field=models.CharField(max_length=255),
        ),
    ]
