# Generated by Django 5.2.1 on 2025-05-30 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_alter_solicitud_options_alter_solicitud_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_subida',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='validado_por',
            field=models.CharField(default='Ninguno', max_length=255),
        ),
    ]
